import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { and, eq } from "drizzle-orm";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { notifyOwner } from "./_core/notification";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { complaints, complaintHistory, notices, appSettings, notificationEvents } from "../drizzle/schema";
import { getDb, getComplaint, getHistory, listComplaints, listNotices, listNotifications, listResidents, analytics, getSettings, recordNotification, refreshOverdueFlags } from "./db";
import { storagePut } from "./storage";
import { canUpdateComplaint } from "../shared/maintenance";
import { sendEmail, sendBroadcast } from "./email";

const categories = ["plumbing", "electrical", "lift", "housekeeping", "security", "other"] as const;
const statuses = ["open", "in_progress", "resolved"] as const;
const priorities = ["low", "medium", "high"] as const;
const adminProcedure = protectedProcedure.use(({ ctx, next }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Admin access required" }); return next(); });

async function ownerAlert(title: string, content: string) { try { const delivered = await notifyOwner({ title, content }); return delivered ? "sent" : "fallback"; } catch { return "fallback"; } }

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(opts => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  complaints: router({
    list: protectedProcedure.query(async ({ ctx }) => { await refreshOverdueFlags(); return listComplaints(ctx.user.role === "admin" ? undefined : ctx.user.id, ctx.user.societyId || undefined); }),
    detail: protectedProcedure.input(z.object({ id: z.number() })).query(async ({ ctx, input }) => { const complaint = await getComplaint(input.id); if (!complaint || (ctx.user.role !== "admin" && complaint.residentId !== ctx.user.id)) throw new TRPCError({ code: "NOT_FOUND" }); return { ...complaint, history: await getHistory(input.id) }; }),
    create: protectedProcedure.input(z.object({ title: z.string().min(3).max(180), category: z.enum(categories), description: z.string().min(3), photoData: z.string().optional(), photoName: z.string().optional(), photoType: z.string().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); let photoUrl: string | undefined; let photoKey: string | undefined; if (input.photoData) { if (!input.photoType?.startsWith("image/")) throw new TRPCError({ code: "BAD_REQUEST", message: "Only image uploads are supported" }); const raw = input.photoData.replace(/^data:[^;]+;base64,/, ""); const uploaded = await storagePut(`complaints/${ctx.user.id}/${input.photoName ?? "maintenance-photo.jpg"}`, Buffer.from(raw, "base64"), input.photoType); photoUrl = uploaded.url; photoKey = uploaded.key; }
      const inserted = await db.insert(complaints).values({ residentId: ctx.user.id, title: input.title, category: input.category, description: input.description, photoUrl, photoKey, priority: "medium", status: "open", isOverdue: false, societyId: ctx.user.societyId }).returning({ id: complaints.id }); const complaintId = inserted[0].id; await db.insert(complaintHistory).values({ complaintId, previousStatus: null, newStatus: "open", changedByUserId: ctx.user.id, adminNote: "Complaint submitted" }); const alertStatus = await ownerAlert("New maintenance complaint", `${input.title} was submitted by ${ctx.user.name ?? "a resident"}.`); await recordNotification({ eventType: "owner_alert", complaintId, recipientEmail: null, status: alertStatus as "sent" | "fallback", message: "Owner alert for new complaint" }); return { id: complaintId }; }),
    update: adminProcedure.input(z.object({ id: z.number(), status: z.enum(statuses), priority: z.enum(priorities), note: z.string().max(1000).optional(), assignedAdminId: z.number().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const existing = await getComplaint(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND" }); if (!canUpdateComplaint(existing.status)) throw new TRPCError({ code: "BAD_REQUEST", message: "Resolved complaints are permanently closed" }); await db.update(complaints).set({ status: input.status, priority: input.priority, assignedAdminId: input.assignedAdminId ?? ctx.user.id, resolutionNote: input.status === "resolved" ? input.note ?? null : existing.resolutionNote, isOverdue: false }).where(eq(complaints.id, input.id)); if (existing.status !== input.status) await db.insert(complaintHistory).values({ complaintId: input.id, previousStatus: existing.status, newStatus: input.status, changedByUserId: ctx.user.id, adminNote: input.note ?? null }); const message = `Your complaint “${existing.title}” is now ${input.status.replace("_", " ")}.${input.note ? ` Note: ${input.note}` : ""}`; if (existing.residentEmail) { const delivery = await sendEmail({ to: existing.residentEmail, subject: `Complaint update: ${existing.title}`, text: message }); await recordNotification({ eventType: "complaint_status", recipientEmail: existing.residentEmail, complaintId: input.id, status: delivery, message }); } return { success: true }; }),
  }),
  notices: router({ list: protectedProcedure.query(({ ctx }) => listNotices(ctx.user.societyId || undefined)), create: adminProcedure.input(z.object({ title: z.string().min(3).max(180), body: z.string().min(3), category: z.enum(["maintenance", "security", "community", "emergency"]), isPinned: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const inserted = await db.insert(notices).values({ ...input, authorId: ctx.user.id, societyId: ctx.user.societyId }).returning({ id: notices.id }); const noticeId = inserted[0].id; const residents = await listResidents(ctx.user.societyId || undefined); if (input.isPinned) { const emails = residents.flatMap(resident => resident.email ? [resident.email] : []); const delivery = await sendBroadcast(emails, `Important society notice: ${input.title}`, input.body); for (const resident of residents) if (resident.email) await recordNotification({ eventType: "notice_published", recipientEmail: resident.email, noticeId, status: delivery, message: input.title }); const alertStatus = await ownerAlert("Pinned notice published", input.title); await recordNotification({ eventType: "owner_alert", noticeId, recipientEmail: null, status: alertStatus as "sent" | "fallback", message: "Owner alert for high-priority notice" }); } return { id: noticeId }; }) }),
  analytics: router({ overview: adminProcedure.query(() => analytics()) }),
  notifications: router({ mine: protectedProcedure.query(({ ctx }) => listNotifications(ctx.user.email ?? undefined)) }),
  settings: router({ get: protectedProcedure.query(() => getSettings()), update: adminProcedure.input(z.object({ overdueThresholdDays: z.number().int().min(1).max(90) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const current = await getSettings(); if ("id" in current && current.id) await db.update(appSettings).set({ overdueThresholdDays: input.overdueThresholdDays, updatedByUserId: ctx.user.id }).where(eq(appSettings.id, current.id)); else await db.insert(appSettings).values({ overdueThresholdDays: input.overdueThresholdDays, updatedByUserId: ctx.user.id }); return { success: true }; }) }),
});
export type AppRouter = typeof appRouter;
